import { TemplateStyles } from "@/lib/types";

export interface TemplatePreset {
  id: string;
  name: string;
  description: string;
  styles: TemplateStyles;
}

export const templatePresets: TemplatePreset[] = [
  {
    id: "vintage-red",
    name: "Vintage Red",
    description: "Classic professional design with warm red tones and elegant typography",
    styles: {
      primaryColor: "#b91c1c",
      accentColor: "#fbbf24",
      fontFamily: "lato",
      headerStyle: "center",
      showLogo: true,
      showBorder: true,
      showWatermark: false,
      tableStyle: "bordered",
    },
  },
  {
    id: "creative-yellow",
    name: "Creative Yellow",
    description: "Bold and energetic design perfect for creative businesses",
    styles: {
      primaryColor: "#ca8a04",
      accentColor: "#0ea5e9",
      fontFamily: "poppins",
      headerStyle: "left",
      showLogo: true,
      showBorder: false,
      showWatermark: false,
      tableStyle: "minimal",
    },
  },
  {
    id: "eco-green",
    name: "Eco Green",
    description: "Fresh and natural design for eco-conscious businesses",
    styles: {
      primaryColor: "#15803d",
      accentColor: "#84cc16",
      fontFamily: "opensans",
      headerStyle: "left",
      showLogo: true,
      showBorder: true,
      showWatermark: false,
      tableStyle: "striped",
    },
  },
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    description: "Professional and trustworthy design for established businesses",
    styles: {
      primaryColor: "#1e40af",
      accentColor: "#06b6d4",
      fontFamily: "inter",
      headerStyle: "left",
      showLogo: true,
      showBorder: true,
      showWatermark: false,
      tableStyle: "striped",
    },
  },
  {
    id: "modern-purple",
    name: "Modern Purple",
    description: "Sleek and contemporary design with a creative edge",
    styles: {
      primaryColor: "#7c3aed",
      accentColor: "#ec4899",
      fontFamily: "poppins",
      headerStyle: "center",
      showLogo: true,
      showBorder: false,
      showWatermark: false,
      tableStyle: "minimal",
    },
  },
  {
    id: "elegant-black",
    name: "Elegant Black",
    description: "Sophisticated and minimalist design for premium services",
    styles: {
      primaryColor: "#18181b",
      accentColor: "#a1a1aa",
      fontFamily: "inter",
      headerStyle: "right",
      showLogo: true,
      showBorder: true,
      showWatermark: false,
      tableStyle: "bordered",
    },
  },
  {
    id: "coastal-sand",
    name: "Coastal Sand",
    description: "Calm navy and sand tones for consultants, hospitality, and lifestyle brands",
    styles: {
      primaryColor: "#164e63",
      accentColor: "#d6b981",
      fontFamily: "lato",
      headerStyle: "right",
      showLogo: true,
      showBorder: true,
      showWatermark: false,
      tableStyle: "minimal",
    },
  },
  {
    id: "rose-studio",
    name: "Rose Studio",
    description: "Refined plum and rose palette made for studios, events, and beauty businesses",
    styles: {
      primaryColor: "#831843",
      accentColor: "#fb7185",
      fontFamily: "poppins",
      headerStyle: "center",
      showLogo: true,
      showBorder: false,
      showWatermark: false,
      tableStyle: "striped",
    },
  },
  {
    id: "midnight-cyan",
    name: "Midnight Cyan",
    description: "High-contrast midnight and cyan design for technology and digital services",
    styles: {
      primaryColor: "#0f172a",
      accentColor: "#22d3ee",
      fontFamily: "roboto",
      headerStyle: "left",
      showLogo: true,
      showBorder: true,
      showWatermark: false,
      tableStyle: "minimal",
    },
  },
  {
    id: "copper-ledger",
    name: "Copper Ledger",
    description: "Warm copper and charcoal styling for trades, construction, and professional services",
    styles: {
      primaryColor: "#3f3f46",
      accentColor: "#c2410c",
      fontFamily: "opensans",
      headerStyle: "right",
      showLogo: true,
      showBorder: true,
      showWatermark: false,
      tableStyle: "bordered",
    },
  },
  {
    id: "soft-lavender",
    name: "Soft Lavender",
    description: "Friendly lavender and violet design with a clean centered presentation",
    styles: {
      primaryColor: "#5b21b6",
      accentColor: "#c4b5fd",
      fontFamily: "poppins",
      headerStyle: "center",
      showLogo: true,
      showBorder: false,
      showWatermark: false,
      tableStyle: "minimal",
    },
  },
  {
    id: "monochrome-grid",
    name: "Monochrome Grid",
    description: "Crisp black-and-white layout with structured tables for detailed invoices",
    styles: {
      primaryColor: "#111827",
      accentColor: "#6b7280",
      fontFamily: "inter",
      headerStyle: "left",
      showLogo: true,
      showBorder: true,
      showWatermark: false,
      tableStyle: "bordered",
    },
  },
  {
    id: "african-sunrise",
    name: "African Sunrise",
    description: "Rich burgundy and amber tones inspired by a warm southern African sunrise",
    styles: {
      primaryColor: "#7f1d1d",
      accentColor: "#f59e0b",
      fontFamily: "lato",
      headerStyle: "center",
      showLogo: true,
      showBorder: true,
      showWatermark: false,
      tableStyle: "striped",
    },
  },
  {
    id: "executive-watermark",
    name: "Executive Watermark",
    description: "Formal navy document with a subtle watermark for proposals and premium accounts",
    styles: {
      primaryColor: "#172554",
      accentColor: "#94a3b8",
      fontFamily: "roboto",
      headerStyle: "right",
      showLogo: true,
      showBorder: true,
      showWatermark: true,
      tableStyle: "minimal",
    },
  },
];
