import type { LucideIcon } from "lucide-react";
import { ArrowUpRight, Blocks, Bot, FileText, Globe2, MessageSquareText, Monitor, ReceiptText, Palette, PanelsTopLeft, QrCode, Smartphone, Sparkles, Workflow } from "lucide-react";

type Product = { name: string; label: string; description: string; href: string; icon: LucideIcon; kind: "qr" | "invoice" | "sms" | "pos"; current?: boolean };
const products: Product[] = [
  { name: "IEOSUIA QR", label: "QR management", description: "Create, update, and track smart QR codes.", href: "https://qr.ieosuia.com/", icon: QrCode, kind: "qr" },
  { name: "IEOSUIA Invoices", label: "Business finance", description: "Create professional invoices, quotes, and track payments.", href: "https://invoices.ieosuia.com/", icon: FileText, kind: "invoice", current: true },
  { name: "IEOSUIA SMS Portal", label: "Messaging platform", description: "Manage audiences, send SMS campaigns, and monitor delivery.", href: "https://sms.ieosuia.com/", icon: MessageSquareText, kind: "sms" },
  { name: "IEOSUIA POS", label: "Cloud point of sale", description: "Run sales, track stock, manage staff, and review receipts and reports.", href: "https://pos.ieosuia.com/", icon: Monitor, kind: "pos" },
];
const services: Array<{ name: string; description: string; icon: LucideIcon }> = [
  { name: "Websites", description: "Modern web experiences", icon: Globe2 }, { name: "Mobile Apps", description: "Apps for Android and iOS", icon: Smartphone },
  { name: "Business Software", description: "Tools for operations and growth", icon: Blocks }, { name: "AI Solutions", description: "Practical AI for real workflows", icon: Bot },
  { name: "Automation", description: "Reduce repetitive work", icon: Workflow }, { name: "Graphic Design", description: "Brand and marketing visuals", icon: Palette },
  { name: "UI/UX Design", description: "Interface and experience design", icon: PanelsTopLeft }, { name: "Animation & Motion", description: "Motion for products and campaigns", icon: Sparkles },
];

const productThemes = {
  pos: { label: "text-orange-300", badge: "bg-orange-300 text-slate-950", current: "border-orange-300/50 bg-[#29180d] ring-orange-300/20", hover: "hover:border-orange-300/50 focus-visible:ring-orange-300", action: "bg-orange-400 text-slate-950 group-hover:bg-orange-300", currentAction: "border-orange-300/30 bg-orange-300/10 text-orange-200" },
  qr: { label: "text-cyan-300", badge: "bg-cyan-300 text-slate-950", current: "border-cyan-300/50 bg-[#0a1b31] ring-cyan-300/20", hover: "hover:border-cyan-300/50 focus-visible:ring-cyan-300", action: "bg-cyan-400 text-slate-950 group-hover:bg-cyan-300", currentAction: "border-cyan-300/30 bg-cyan-300/10 text-cyan-200" },
  invoice: { label: "text-emerald-300", badge: "bg-emerald-300 text-emerald-950", current: "border-emerald-300/50 bg-[#0a201f] ring-emerald-300/20", hover: "hover:border-emerald-300/50 focus-visible:ring-emerald-300", action: "bg-emerald-400 text-emerald-950 group-hover:bg-emerald-300", currentAction: "border-emerald-300/30 bg-emerald-300/10 text-emerald-200" },
  sms: { label: "text-sky-300", badge: "bg-sky-300 text-slate-950", current: "border-sky-300/50 bg-[#0a1830] ring-sky-300/20", hover: "hover:border-sky-300/50 focus-visible:ring-sky-300", action: "bg-sky-400 text-slate-950 group-hover:bg-sky-300", currentAction: "border-sky-300/30 bg-sky-300/10 text-sky-200" },
} as const;

const ProductVisual = ({ kind, Icon }: { kind: Product["kind"]; Icon: LucideIcon }) => <div className={`relative h-48 overflow-hidden border-b border-white/10 ${kind === "qr" ? "bg-[radial-gradient(circle_at_78%_18%,rgba(34,211,238,.4),transparent_35%),linear-gradient(145deg,#082f49,#071426)]" : kind === "invoice" ? "bg-[radial-gradient(circle_at_78%_18%,rgba(52,211,153,.35),transparent_35%),linear-gradient(145deg,#064e3b,#071b1b)]" : "bg-[radial-gradient(circle_at_78%_18%,rgba(56,189,248,.38),transparent_35%),linear-gradient(145deg,#12306b,#071426)]"}`}>
  {kind === "pos" && <div aria-hidden="true" className="absolute inset-0 bg-[radial-gradient(circle_at_78%_18%,rgba(251,146,60,.38),transparent_35%),linear-gradient(145deg,#63320c,#1c130b)]"/>}
  <div className="absolute inset-0 opacity-20 [background-image:linear-gradient(rgba(255,255,255,.14)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.14)_1px,transparent_1px)] [background-size:24px_24px]"/>
  <span className="absolute left-5 top-5 grid h-11 w-11 place-items-center rounded-xl border border-white/20 bg-slate-950/30 text-white shadow-lg backdrop-blur"><Icon aria-hidden="true" className="h-5 w-5"/></span>
  {kind === "qr" && <div aria-hidden="true" className="absolute -bottom-3 left-8 right-5 flex items-end gap-4">
    <div className="relative rotate-[-4deg] rounded-2xl border border-cyan-100/70 bg-white p-3 shadow-2xl"><QrCode className="h-24 w-24 text-slate-950"/><span className="absolute -right-2 -top-2 h-5 w-5 rounded-full border-4 border-cyan-300 bg-slate-950"/></div>
    <div className="mb-7 flex-1 rounded-xl border border-cyan-200/25 bg-slate-950/75 p-3 shadow-xl backdrop-blur"><div className="flex items-end justify-between gap-1.5 h-12">{[45,72,56,94,67,84].map((height,index)=><span key={index} className="flex-1 rounded-t bg-gradient-to-t from-blue-500 to-cyan-300" style={{height:`${height}%`}}/>)}</div><div className="mt-2 flex items-center justify-between text-[10px]"><span className="text-slate-300">Live scans</span><strong className="text-cyan-300">1,284</strong></div></div>
  </div>}
  {kind === "invoice" && <div aria-hidden="true" className="absolute -bottom-5 left-8 right-6 flex items-end gap-4">
    <div className="w-[68%] rotate-[-3deg] rounded-t-2xl border border-emerald-100/70 bg-white p-4 text-slate-900 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[8px] font-extrabold tracking-[.18em] text-emerald-700">INVOICE</p><p className="mt-1 text-[9px] font-bold">INV-2026-0042</p></div><span className="rounded-full bg-emerald-100 px-2 py-1 text-[8px] font-bold text-emerald-700">PAID</span></div><div className="mt-4 space-y-2"><span className="block h-1.5 w-full rounded bg-slate-200"/><span className="block h-1.5 w-3/4 rounded bg-slate-200"/><span className="block h-1.5 w-5/6 rounded bg-slate-200"/></div><div className="mt-4 flex justify-between border-t border-slate-200 pt-2 text-[9px]"><span>Total</span><strong>R 4,025.00</strong></div></div>
    <div className="mb-8 flex-1 rounded-xl border border-emerald-200/25 bg-slate-950/75 p-3 shadow-xl backdrop-blur"><span className="text-[9px] text-slate-300">Paid this month</span><strong className="mt-1 block text-lg text-emerald-300">R 28.9k</strong><span className="mt-2 block h-1.5 rounded bg-white/10"><span className="block h-full w-[82%] rounded bg-emerald-400"/></span></div>
  </div>}
  {kind === "pos" && <div aria-hidden="true" className="absolute bottom-0 left-7 right-6 flex items-end gap-3">
    <div className="mb-5 min-w-0 flex-1 rotate-[-3deg] rounded-xl border-4 border-slate-900 bg-white p-3 shadow-2xl"><p className="text-[9px] font-bold uppercase tracking-wider text-orange-800">Point of sale</p><div className="mt-3 grid grid-cols-2 gap-2">{["Sales","Stock","Staff","Reports"].map(label=><span key={label} className="rounded bg-orange-50 px-1 py-3 text-center text-[9px] font-semibold text-slate-800">{label}</span>)}</div></div>
    <div className="mb-7 w-20 rotate-[4deg] rounded-t-lg border border-orange-100 bg-white p-3 text-slate-900 shadow-xl"><ReceiptText className="mx-auto h-7 w-7 text-orange-700"/><p className="mt-2 text-center text-[8px] font-bold">Receipts</p><span className="mt-3 block h-1 rounded bg-slate-200"/><span className="mt-2 block h-1 w-3/4 rounded bg-slate-200"/></div>
  </div>}
  {kind === "sms" && <div aria-hidden="true" className="absolute -bottom-4 left-7 right-6 flex items-end gap-4">
    <div className="w-[45%] rotate-[-3deg] rounded-t-[1.5rem] border-[5px] border-slate-900 bg-white p-2 pb-6 shadow-2xl"><span className="mx-auto block h-1 w-8 rounded bg-slate-300"/><div className="mt-3 rounded-lg rounded-bl-sm bg-sky-100 p-2 text-[8px] font-semibold text-slate-700">Your campaign is live.</div><div className="ml-4 mt-2 rounded-lg rounded-br-sm bg-sky-500 p-2 text-[8px] font-semibold text-white">Delivery looks great!</div></div>
    <div className="mb-7 flex-1 rounded-xl border border-sky-200/25 bg-slate-950/75 p-3 shadow-xl backdrop-blur"><div className="flex items-center justify-between text-[9px]"><span className="text-slate-300">Campaign delivery</span><strong className="text-sky-300">92%</strong></div><div className="mt-3 h-2 rounded bg-white/10"><span className="block h-full w-[92%] rounded bg-gradient-to-r from-blue-500 to-sky-300"/></div><div className="mt-3 grid grid-cols-2 gap-2 text-center text-[8px]"><span className="rounded bg-white/5 p-1.5 text-slate-300"><b className="block text-xs text-white">4,812</b>Delivered</span><span className="rounded bg-white/5 p-1.5 text-slate-300"><b className="block text-xs text-white">388</b>Queued</span></div></div>
  </div>}
</div>;

export function EcosystemSection(){return <section data-ecosystem="invoices" aria-labelledby="ecosystem-heading" className="relative overflow-hidden border-t border-border bg-background text-foreground"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_10%,rgba(8,145,178,.16),transparent_30%),radial-gradient(circle_at_90%_25%,rgba(37,99,235,.13),transparent_34%)]"/><div className="container relative mx-auto px-4 py-16 lg:py-20">
  <div className="flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-primary">More to discover</p><h2 id="ecosystem-heading" className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">Explore more from the IEOSUIA ecosystem</h2><p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground">Discover more IEOSUIA products and digital service categories built to help businesses work smarter.</p></div><a href="https://ieosuia.com/" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 w-fit items-center gap-3 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground transition hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">Explore digital services <ArrowUpRight className="h-4 w-4"/></a></div>
  <div className="mt-10"><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-semibold uppercase tracking-[.18em] text-foreground">IEOSUIA products</h3><span className="text-xs text-muted-foreground md:hidden">Swipe to explore</span></div><div className="-mx-4 flex snap-x snap-mandatory gap-4 overflow-x-auto px-4 pb-4 [scrollbar-color:#155e75_transparent] md:mx-0 md:grid md:grid-cols-2 xl:grid-cols-4 md:overflow-visible md:px-0">{products.map(({name,label,description,href,icon:Icon,kind,current})=>{const theme=productThemes[kind];const card=<><ProductVisual kind={kind} Icon={Icon}/><div className="flex min-h-52 flex-1 flex-col p-5"><div className="flex min-h-9 items-center justify-between gap-3"><p className={`text-[11px] font-bold uppercase tracking-[.18em] ${theme.label}`}>{label}</p>{current&&<span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${theme.badge}`}>Current product</span>}</div><h4 className="mt-4 text-xl font-bold">{name}</h4><p className="mt-2 text-sm leading-6 text-slate-400">{description}</p><span className={`mt-auto inline-flex min-h-11 items-center justify-between rounded-lg px-4 py-3 text-sm font-bold ${current?`border ${theme.currentAction}`:theme.action}`}>{current?"You are here":"Explore product"}<ArrowUpRight className="h-4 w-4"/></span></div></>;const classes=`group flex w-[84vw] max-w-sm shrink-0 flex-col snap-start overflow-hidden rounded-2xl border text-left text-white shadow-[0_22px_70px_rgba(0,0,0,.24)] transition md:w-auto md:max-w-none ${current?`${theme.current} ring-1`: `border-white/10 bg-[#091426] hover:-translate-y-1 focus-visible:outline-none focus-visible:ring-2 ${theme.hover}`}`;return current?<article data-product={kind} key={name} className={classes}>{card}</article>:<a data-product={kind} key={name} href={href} aria-label={`Explore ${name}`} className={classes}>{card}</a>})}</div></div>
  <div className="mt-10 border-t border-border pt-8"><h3 className="text-sm font-semibold uppercase tracking-[.18em] text-foreground">Digital service categories</h3><div id="ecosystem-services" role="region" aria-label="Digital service categories. Scroll to explore all eight." tabIndex={0} className="-mx-4 mt-5 flex snap-x gap-3 overflow-x-auto px-4 pb-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring md:mx-0 md:grid md:grid-cols-4 md:px-0">{services.map(({name,description,icon:Icon})=><article key={name} className="min-h-36 w-56 shrink-0 snap-start rounded-xl border border-border bg-card p-4 transition hover:border-primary/40 hover:bg-muted md:w-auto"><span className="grid h-10 w-10 place-items-center rounded-lg bg-primary/10 text-primary"><Icon aria-hidden="true" className="h-5 w-5"/></span><h4 className="mt-4 font-bold">{name}</h4><p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p></article>)}</div></div>
</div></section>}
